# https://www.baeldung.com/linux/ansible-add-user-password-group
- name: create munge and slurm user
  hosts:
    - master
    - workers
  become: yes
  tasks:
    - name: make munge group
      ansible.builtin.group:
        name: munge
        state: present
        gid: 1111
    - name: make slurm group
      ansible.builtin.group:
        name: slurm
        state: present
        gid: 1121
    - name: Create password locked user
      ansible.builtin.user:
        name: munge
        uid: 1111
        comment: ""
        group: munge
        state: present
        password: ''            # login without password with '' or passwd -d slurm at tty
    - name: Create password locked user
      ansible.builtin.user:
        name: slurm
        uid: 1121
        comment: ""
        group: slurm
        state: present
        password: ''             # login without password with '' or passwd -d slurm at tty

- name: install munge
  hosts: master
  become: yes
  tasks:
    - name: master install
      ansible.builtin.apt:
        pkg:
        - libmunge-dev 
        - libmunge2 
        - munge
      state: present
    - name: Enable service munge
      ansible.builtin.systemd_service:
        name: munge
        state: started
        enabled: true
    - name: copy munge.key
      ansible.builtin.copy:
        src: /etc/munge/munge.key
        dest: /mnt/efs
        owner: munge
        mode: 400

    
