# https://www.baeldung.com/linux/ansible-add-user-password-group
- name: create munge and slurm user
  hosts:
    - master
    - workers
  become: yes
  tasks:
    - name: make munge group
      ansible.builtin.group:
        name: munge
        state: present
        gid: 1111
    - name: make slurm group
      ansible.builtin.group:
        name: slurm
        state: present
        gid: 1121
    - name: Create password locked user
      ansible.builtin.user:
        name: munge
        uid: 1111
        comment: ""
        group: munge
        state: present
        password: ''            # login without password with '' or passwd -d slurm at tty
    - name: Create password locked user
      ansible.builtin.user:
        name: slurm
        uid: 1121
        comment: ""
        group: slurm
        state: present
        password: ''             # login without password with '' or passwd -d slurm at tty

- name: install munge on cluster master
  hosts: master
  become: yes
  tasks:
      - name: install
        ansible.builtin.apt:
          pkg:
          - libmunge-dev 
          - libmunge2 
          - munge
          state: present
      - name: enable service
        ansible.builtin.systemd_service:
          name: munge
          state: started
          enabled: true
      - name: copy munge.key to /mnt/efs
        ansible.builtin.copy:
          src: /etc/munge/munge.key
          dest: /mnt/efs
          owner: munge
          group: munge
          mode: "0400"
          remote_src: true
- name: install munge on cluster workers   
  hosts: workers
  become: yes
  tasks:
      - name: install
        ansible.builtin.apt:
          pkg:
          - libmunge-dev 
          - libmunge2 
          - munge
          state: present
      - name: copy munge.key from /mnt/efs
        ansible.builtin.copy:
            src:  /mnt/efs/munge.key
            dest: /etc/munge/munge.key
            owner: munge
            group: munge
            mode: "0400"
            remote_src: true
      - name: enable service
        ansible.builtin.systemd_service:
            name: munge
            state: started
            enabled: true
   
        
