- hosts: all
  gather_facts: yes
  tasks:
    - debug:
        msg: "{{ ansible_hostname }}:{{ ansible_default_ipv4.address }}"
        
- name: gather cluster node information and update /etc/hosts of each node
  hosts: all
  tasks:
  - name: update /etc/hosts
    become: yes
    blockinfile:
      backup: yes
      path: /etc/hosts
      block: |
        {% for host in groups['all'] %} 
        {{ hostvars[host]['ansible_facts']['ens5']['ipv4']['address'] }} {{ hostvars[host]['ansible_facts']['hostname'] }} 
        {% endfor %}

- name: install munge and slurmctld in master
  hosts: master
  become: yes
  tasks:
      - name: install
        ansible.builtin.apt:
          pkg:
          - munge 
          - libmunge-dev 
          - slurm-wlm 
          state: present
      - name: make mungekey
        shell: |
          sudo /usr/sbin/mungekey                              
          sudo cp /etc/munge/munge.key /mnt/efs  
          sudo chown munge:munge /etc/munge/munge.key          
          sudo chmod 400 /etc/munge/munge.key
          sudo mkdir /var/spool/slurm                  
          sudo chown slurm:slurm /var/spool/slurm 
          sudo chmod 777 /var/spool/slurm
      - name: enable service
        ansible.builtin.systemd_service:
          name: munge
          enabled: true
          state: started

- name: install munge and slurmd in workers
  hosts: workers
  become: yes
  tasks:
      - name: install
        ansible.builtin.apt:
          pkg:
          - munge 
          - libmunge-dev 
          - slurmd
          state: present
      - name: copy mungekey from master
        shell: |
          sudo cp /mnt/efs/munge.key /etc/munge/munge.key   
          sudo chown munge:munge /etc/munge/munge.key          
          sudo chmod 400 /etc/munge/munge.key
          sudo mkdir /var/spool/slurm                  
          sudo chown slurm:slurm /var/spool/slurm 
          sudo chmod 777 /var/spool/slurm
      - name: enable service
        ansible.builtin.systemd_service:
          name: munge
          enabled: true
          state: started

- name: install munge and slurmd in client
  hosts: client 
  become: yes
  tasks:
      - name: install
        ansible.builtin.apt:
          pkg:
          - munge 
          - libmunge-dev 
          - slurm-client
          state: present
      - name: copy mungekey from master
        shell: |
          sudo cp /mnt/efs/munge.key /etc/munge/munge.key   
          sudo chown munge:munge /etc/munge/munge.key          
          sudo chmod 400 /etc/munge/munge.key
          sudo mkdir /var/spool/slurm                  
          sudo chown slurm:slurm /var/spool/slurm 
          sudo chmod 777 /var/spool/slurm
      - name: enable service
        ansible.builtin.systemd_service:
          name: munge
          enabled: true
          state: started

- name: copy configuration to slurm cluster
  hosts: all
  become: yes
  tasks:
    - name: slurm.conf
      copy:
        src: ~/slurm-on-grv/slurm/conf/slurm.conf
        dest: /etc/slurm
    - name: cgroup.conf
      copy:
        src: ~/slurm-on-grv/slurm/conf/cgroup.conf
        dest: /etc/slurm    
    - name: gres.conf
      copy:
        src: ~/slurm-on-grv/slurm/conf/gres.conf
        dest: /etc/slurm
  
    

          
